on:
  npm:
    # name: next
    # version: canary
    name: "@ascorbic/gatsby-cli-demo"
    version: latest
jobs:
  test:
    name: Test next.js release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test site
        uses: actions/checkout@v2
        with:
          repository: netlify/netlify-plugin-nextjs
      - name: Install dependencies
        run: npm ci
      - name: Installing new version of Next.js
        run: npm i -D ${{ on.npm.outputs.name }}@${{ on.npm.outputs.version }}
      - name: Run tests
        run: npm test
      - name: Slack fail notification
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.NEXT_SLACK_WEBHOOK }}
          GITHUB_WORKFLOW_URL:
            https://github.com/${{ github.repository }}/actions/runs/${{
            github.run_id }}
        uses: Ilshidur/action-slack@2.0.2
        with:
          args:
            New Next.js canary build failed with ${{ on.npm.outputs.name }}@${{
            on.npm.outputs.version }} \n${{ env.GITHUB_WORKFLOW_URL }}
      - name: Slack succeed notification
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.NEXT_SLACK_WEBHOOK }}
        uses: Ilshidur/action-slack@2.0.2
        with:
          args: New Next canary build succeeded \n${{ env.GITHUB_WORKFLOW_URL }}
