on:
  npm:
    # name: next
    # version: canary
    name: "@ascorbic/gatsby-cli-demo"
    version: latest
jobs:
  test:
    name: Test next.js release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test site
        uses: actions/checkout@v2
        with:
          repository: netlify/netlify-plugin-nextjs
      - name: Install dependencies
        run: npm ci
      - name: Fail
        run: exit 1
      # - name: Installing new version of Next.js
      #   run: npm i -D ${{ on.npm.outputs.name }}@${{ on.npm.outputs.version }}
      # - name: Run tests
      #   run: npm test

      - name: Slack Notification
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.NEXT_SLACK_WEBHOOK }}
          PACKAGE_VERSION: ${{ on.npm.outputs.version }}
        with:
          status: ${{ job.status }}
          success_text: New Next canary build succeeded
          failure_text: New Next canary build failed
          fields: |
            [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"},
              {"title": "Package version", "value": "${env.PACKAGE_VERSION}", short: true}
            ]

        if: always()
