on:
  npm:
    name: next
    version: canary
jobs:
  test:
    name: Test next.js release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test site
        uses: actions/checkout@v2
        with:
          repository: netlify/netlify-plugin-nextjs
      - name: Install dependencies
        run: npm ci
      - name: Installing new version of Next.js
        run: npm i -D ${{ on.npm.outputs.name }}@${{ on.npm.outputs.version }}
      - name: Run tests
        run: npm test
